<?php

namespace VoorraadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReparatieOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparatieOrderRepository extends EntityRepository
{
}
