<?php

namespace VoorraadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReparatieRegelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparatieRegelRepository extends EntityRepository
{
}
